service: my-portfolio-api

plugins:
  - serverless-offline

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  iamRoleStatements:
      - Effect: Allow
        Action:
          - dynamodb:PutItem
        Resource: '*'

package:
  individually: true
  exclude:
    - node_modules/**

functions:
  getblog:
    handler: api/blog.getBlog
    events:
      - http:
          path: api/v1/blog
          method: GET
          cors: true
  miketest:
    handler: api/blog.mikeTest
    events:
      - http:
          path: api/v1/blog/mike-test
          method: GET
          cors: true
custom:
  serverless-offline:
    httpPort: 2300